version: "3"

services:
  node-app:
    build: .
    ports:
      - "4200:3000"
    volumes:
      - ./:/app:ro
      - /app/node_modules
    # environment:
    #     - PORT=3000
    env_file:
      - ./.env
