version: "3"

services:
  node-app:
    build: .
    ports:
      - "4200:3000"
    environment:
      - PORT=3000
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=theHinneh
      - MONGO_INITDB_ROOT_PASSWORD=theHinneh
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis

volumes:
  mongo-db:
